point:
	g++ -o Point Point.cpp -lglut -lGLU -lGL
	
triangle:
	g++ -o Triangle MTriangle.cpp Triangle.cpp Point.cpp Color.cpp -lglut -lGLU -lGL

sierpenski:
	g++ -o Sierpenski Sierpenski.cpp Triangle.cpp Point.cpp Color.cpp -lglut -lGLU -lGL

cube:
	g++ -o cube cube3d.cpp -lglut -lGL -lGLU
