point:
	g++ -o Point MPoint.cpp Point.cpp -lglut -lGLU -lGL

square:
	g++ -o Square MSquare.cpp Square.cpp Point.cpp Color.cpp -lglut -lGLU -lGL

cube:
	g++ -o Cube MCube.cpp Cube.cpp Square.cpp Point.cpp Color.cpp -lglut -lGL -lGLU

rubiks:
	g++ -o Rubiks MRubiks.cpp Rubiks.cpp Cube.cpp Square.cpp Point.cpp Color.cpp -lglut -lGL -lGLU
